FROM golang:latest
WORKDIR /app

COPY . .
RUN go env -w GO111MODULE=auto
RUN go build -o ./store-service-grpc/mongodb-first/main ./store-service-grpc/mongodb-first/main.go
WORKDIR /app/store-service-grpc/mongodb-first
ENTRYPOINT ["./main"]