version: '2'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./etcd_data:/bitnami/etcd

  auth-service:
    image: registry.cn-hangzhou.aliyuncs.com/datapulse/auth-service
    container_name: auth-service

  gateway-service:
    image: registry.cn-hangzhou.aliyuncs.com/datapulse/gateway-service
    container_name: gateway-service
    ports:
      - 8080:8080

  redis:
    restart: always
    image: redis
    container_name: redis
    networks:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  dockerupdate:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock