FROM golang:latest
WORKDIR /app

COPY . .
RUN go env -w GO111MODULE=auto
RUN go build -o ./store-service-grpc/mysql-second/main ./store-service-grpc/mysql-second/main.go
WORKDIR /app/store-service-grpc/mysql-second
ENTRYPOINT ["./main"]