# Gin web服务配置
server:
  Name: "store-service"
  Addr: "store-service:8083"
# GRPC 服务配置
etcd:
  Name: "etcd"
  Addrs:
    - "etcd:2379"
# 数据库配置
mysql:
  Host: "222.186.50.126:20134"
  Name: "root"
  Password: "maojiukeai1412"
