# Gin web服务配置
server:
  Name: "log-service"
  Addr: "localhost:8082"
# 数据库配置
redis:
  Host: "localhost:6379"
  Password: ""
  Db: 0
mysql:
  Host: "localhost:3306"
  Name: "root"
  Password: "123698745"
