# Gin web服务配置
server:
  Name: "auth-service"
  Addr: "localhost:8081"
# 数据库配置
redis:
  Host: "8.130.84.188:6379"
  Password: ""
  Db: 0
mysql:
  Host: "222.186.50.126:20134"
  Name: "root"
  Password: "maojiukeai1412"
# 邮件发送配置
smtp:
  Host: "smtp.fastmail.com"
  Username: "sora@resoras.com"
  Password: "uysx8mlv49nnhcwk"
  Fromname: "notifications@sent.com"
