# Gin web服务配置
server:
  Name: "auth-service"
  Addr: "auth-service:8081"
# GRPC 服务配置
grpc:
  Name: "auth"
  Addr: "auth-service:9000"
  Version: "1.0"
  Weight: 1
etcd:
  Name: "etcd"
  Addrs:
    - "etcd:2379"
# 数据库配置
redis:
  Host: "redis:6379"
  Password: ""
  Db: 0
mysql:
  Host: "222.186.50.126:20134"
  Name: "root"
  Password: "maojiukeai1412"
# 邮件发送配置
smtp:
  Host: "smtp.fastmail.com"
  Username: "sora@resoras.com"
  Password: "uysx8mlv49nnhcwk"
  Fromname: "notifications@sent.com"
