# Gin web服务配置
server:
  Name: "auth-service"
  Addr: "localhost:8081"
# GRPC 服务配置
grpc:
  Name: "auth"
  Addr: "localhost:9000"
  Version: "1.0"
  Weight: 1
etcd:
  Name: "etcd"
  Addrs:
    - "8.130.84.188:2379"
# 数据库配置
redis:
  Host: "localhost:6379"
  Password: ""
  Db: 0
mysql:
  Host: "localhost:3306"
  Name: "root"
  Password: "123698745"
