# Gin web服务配置
server:
  Name: "task-service"
  Addr: "task-service:8084"
# GRPC 服务配置
etcd:
  Name: "etcd"
  Addrs:
    - "etcd:2379"
# 数据库配置
mysql:
  Host: "localhost:3306"
  Name: "root"
  Password: "123698745"
