name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # 可以根据你的需求更改触发条件

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push auth-service
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/datapulse/auth-service -f Dockerfile.auth-service .
          docker push registry.cn-hangzhou.aliyuncs.com/datapulse/auth-service

      - name: Build and push gateway-service
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/datapulse/gateway-service -f Dockerfile.gateway-service .
          docker push registry.cn-hangzhou.aliyuncs.com/datapulse/gateway-service
